/* Default subjects (sample end-sem syllabus — replace with your university syllabus
   from the "Syllabus" tab inside the app) and daily motivation quotes. */
window.ES_DEFAULT_SUBJECTS = [
  {
    id: 'phy', name: 'Physics', short: 'PHY', color: '#6366f1', kind: 'numerical', priority: 3, examDate: '',
    syllabus: [
      '# Unit 1: Quantum Mechanics',
      'Dual nature of matter & de Broglie hypothesis',
      'Heisenberg uncertainty principle',
      'Wave function and its physical significance',
      'Schrodinger time-independent wave equation',
      'Particle in a one-dimensional box',
      '# Unit 2: Lasers & Fibre Optics',
      'Spontaneous and stimulated emission, Einstein coefficients',
      'Population inversion and pumping methods',
      'He-Ne laser and semiconductor laser',
      'Applications of lasers',
      'Optical fibre: principle (TIR), numerical aperture, acceptance angle',
      'Types of optical fibres and losses',
      '# Unit 3: Semiconductor Physics',
      'Band theory of solids',
      'Intrinsic and extrinsic semiconductors, Fermi level',
      'Hall effect',
      'P-N junction diode, LED and solar cell',
      '# Unit 4: Wave Optics',
      'Interference in thin films',
      "Newton's rings",
      'Diffraction: single slit and diffraction grating',
      "Polarization and Malus' law",
      '# Unit 5: Superconductivity & Nanomaterials',
      'Superconductivity: Meissner effect, Type I & II',
      'BCS theory (basics) and applications of superconductors',
      'Nanomaterials: properties and synthesis methods'
    ].join('\n')
  },
  {
    id: 'mat', name: 'Mathematics', short: 'MATH', color: '#0284c7', kind: 'numerical', priority: 3, examDate: '',
    syllabus: [
      '# Unit 1: Matrices',
      'Rank of a matrix, echelon & normal form',
      'Consistency of system of linear equations',
      'Eigenvalues and eigenvectors',
      'Cayley-Hamilton theorem',
      'Diagonalization of matrices',
      '# Unit 2: Differential Calculus',
      'Successive differentiation & Leibniz theorem',
      "Taylor's and Maclaurin's series",
      'Indeterminate forms',
      "Partial differentiation & Euler's theorem",
      'Maxima and minima of two variables',
      "Lagrange's method of multipliers",
      '# Unit 3: Integral Calculus',
      'Beta and Gamma functions',
      'Double integrals & change of order',
      'Triple integrals',
      'Area and volume using multiple integrals',
      '# Unit 4: Ordinary Differential Equations',
      'Exact and linear first order ODEs, Bernoulli equation',
      'Higher order linear ODE with constant coefficients',
      'Method of variation of parameters',
      '# Unit 5: Sequences & Series',
      'Convergence of sequences and series',
      'Comparison, ratio and root tests',
      'Fourier series (basics)'
    ].join('\n')
  },
  {
    id: 'prog', name: 'Computer Programming', short: 'CP', color: '#ea580c', kind: 'coding', priority: 3, examDate: '',
    syllabus: [
      '# Unit 1: Basics',
      'Algorithms and flowcharts',
      'Structure of a C program, data types, variables & constants',
      'Operators and expressions, type conversion',
      'Input / output functions',
      '# Unit 2: Control Flow',
      'Decision making: if, if-else, switch',
      'Loops: for, while, do-while',
      'break, continue and nested loops (pattern programs)',
      '# Unit 3: Arrays & Strings',
      '1-D arrays: searching and sorting',
      '2-D arrays and matrix programs',
      'Strings and string library functions',
      '# Unit 4: Functions & Pointers',
      'Functions, call by value & call by reference',
      'Recursion',
      'Pointers and pointer arithmetic',
      'Pointers with arrays and functions',
      '# Unit 5: Structures & Files',
      'Structures and unions',
      'Dynamic memory allocation (malloc, calloc, free)',
      'File handling in C'
    ].join('\n')
  },
  {
    id: 'iks', name: 'IKS (Indian Knowledge System)', short: 'IKS', color: '#ca8a04', kind: 'theory', priority: 2, examDate: '',
    syllabus: [
      '# Unit 1: Introduction',
      'Introduction to Indian Knowledge System & its relevance',
      'Vedas, Upanishads and Vedic literature',
      '# Unit 2: Philosophy & Wellbeing',
      'Indian philosophical systems (Darshanas)',
      'Yoga and Ayurveda: health and wellness',
      '# Unit 3: Science & Mathematics',
      'Ancient Indian mathematics (Aryabhata, Brahmagupta, Bhaskara)',
      'Indian astronomy',
      'Metallurgy and technology in ancient India',
      '# Unit 4: Society & Culture',
      'Architecture, town planning and Vastu',
      'Indian languages and linguistics (Panini)',
      'Governance and economics (Arthashastra)'
    ].join('\n')
  },
  {
    id: 'ob', name: 'OB (Organizational Behaviour)', short: 'OB', color: '#db2777', kind: 'theory', priority: 2, examDate: '',
    syllabus: [
      '# Unit 1: Introduction',
      'Nature, scope and importance of OB',
      'Models of OB and challenges',
      '# Unit 2: Individual Behaviour',
      'Personality: determinants and theories',
      'Perception and attribution',
      'Learning theories',
      'Attitudes, values and job satisfaction',
      '# Unit 3: Motivation & Leadership',
      'Motivation theories: Maslow, Herzberg, McGregor',
      'Leadership styles and theories',
      '# Unit 4: Group Behaviour',
      'Group dynamics and team building',
      'Communication in organizations',
      'Conflict management and negotiation',
      '# Unit 5: Organization',
      'Organizational culture',
      'Organizational change and stress management'
    ].join('\n')
  },
  {
    id: 'uhv', name: 'UHV (Universal Human Values)', short: 'UHV', color: '#9333ea', kind: 'theory', priority: 2, examDate: '',
    syllabus: [
      '# Unit 1: Value Education',
      'Need, basic guidelines and content of value education',
      'Self-exploration: process and content',
      'Happiness and prosperity: basic human aspirations',
      '# Unit 2: Harmony in the Human Being',
      "Human being as co-existence of the Self ('I') and the Body",
      'Harmony of the Self with the Body (Sanyam & Health)',
      '# Unit 3: Harmony in Family & Society',
      'Trust and respect: foundational values in relationships',
      'Harmony in society: undivided society & universal order',
      '# Unit 4: Harmony in Nature & Existence',
      'Four orders of nature and their interconnectedness',
      'Existence as co-existence',
      '# Unit 5: Professional Ethics',
      'Natural acceptance of human values & ethical conduct',
      'Competence in professional ethics, case studies'
    ].join('\n')
  },
  {
    id: 'env', name: 'Environmental Science', short: 'ENV', color: '#16a34a', kind: 'theory', priority: 2, examDate: '',
    syllabus: [
      '# Unit 1: Environment & Natural Resources',
      'Multidisciplinary nature of environmental studies',
      'Natural resources: forest, water and mineral',
      'Natural resources: food, energy and land',
      '# Unit 2: Ecosystems & Biodiversity',
      'Ecosystem: structure, function, food chains and webs',
      'Biodiversity: values, threats and conservation',
      '# Unit 3: Pollution',
      'Air pollution: causes, effects and control',
      'Water and soil pollution',
      'Noise pollution and solid waste management',
      '# Unit 4: Global Issues & Laws',
      'Climate change, global warming, acid rain, ozone depletion',
      'Environmental protection acts in India',
      '# Unit 5: Human Population & Disasters',
      'Population growth and its impact on environment',
      'Disaster management: floods, earthquakes, cyclones'
    ].join('\n')
  }
];

window.ES_QUOTES = [
  { q: 'Arise, awake, and stop not till the goal is reached.', a: 'Swami Vivekananda' },
  { q: 'You have to dream before your dreams can come true.', a: 'A. P. J. Abdul Kalam' },
  { q: 'Excellence is a continuous process and not an accident.', a: 'A. P. J. Abdul Kalam' },
  { q: 'If you want to shine like a sun, first burn like a sun.', a: 'A. P. J. Abdul Kalam' },
  { q: 'It does not matter how slowly you go as long as you do not stop.', a: 'Confucius' },
  { q: 'Success is the sum of small efforts, repeated day in and day out.', a: 'Robert Collier' },
  { q: "Don't watch the clock; do what it does. Keep going.", a: 'Sam Levenson' },
  { q: 'Education is the most powerful weapon which you can use to change the world.', a: 'Nelson Mandela' },
  { q: 'You have a right to perform your duties, but not to the fruits of your actions.', a: 'Bhagavad Gita 2.47' },
  { q: 'The future depends on what you do today.', a: 'Mahatma Gandhi' },
  { q: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', a: 'Mahatma Gandhi' },
  { q: 'Discipline is the bridge between goals and accomplishment.', a: 'Jim Rohn' },
  { q: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', a: 'Will Durant' },
  { q: 'Strive for progress, not perfection.', a: 'Unknown' },
  { q: 'Small daily improvements over time lead to stunning results.', a: 'Robin Sharma' },
  { q: 'Push yourself, because no one else is going to do it for you.', a: 'Unknown' },
  { q: 'The beautiful thing about learning is that no one can take it away from you.', a: 'B. B. King' },
  { q: "Believe you can and you're halfway there.", a: 'Theodore Roosevelt' },
  { q: "Hard work beats talent when talent doesn't work hard.", a: 'Tim Notke' },
  { q: 'Genius is one percent inspiration and ninety-nine percent perspiration.', a: 'Thomas Edison' },
  { q: 'Take up one idea. Make that one idea your life.', a: 'Swami Vivekananda' },
  { q: 'All power is within you; you can do anything and everything.', a: 'Swami Vivekananda' },
  { q: 'Focus on being productive instead of busy.', a: 'Tim Ferriss' },
  { q: 'The only way to do great work is to love what you do.', a: 'Steve Jobs' },
  { q: "It always seems impossible until it's done.", a: 'Nelson Mandela' },
  { q: 'Do not let what you cannot do interfere with what you can do.', a: 'John Wooden' },
  { q: 'A little progress each day adds up to big results.', a: 'Unknown' },
  { q: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', a: 'Winston Churchill' },
  { q: "Set your goals high, and don't stop till you get there.", a: 'Bo Jackson' },
  { q: 'Winners are not people who never fail, but people who never quit.', a: 'Unknown' },
  { q: 'Your future is created by what you do today, not tomorrow.', a: 'Robert Kiyosaki' },
  { q: 'The pain you feel today will be the strength you feel tomorrow.', a: 'Unknown' },
  { q: 'One day or day one. You decide.', a: 'Unknown' },
  { q: 'Do something today that your future self will thank you for.', a: 'Sean Patrick Flanery' },
  { q: 'Learning never exhausts the mind.', a: 'Leonardo da Vinci' },
  { q: 'Consistency is what transforms average into excellence.', a: 'Unknown' },
  { q: "Dreams don't work unless you do.", a: 'John C. Maxwell' },
  { q: 'Great things are done by a series of small things brought together.', a: 'Vincent van Gogh' },
  { q: 'An investment in knowledge pays the best interest.', a: 'Benjamin Franklin' },
  { q: 'There are no shortcuts to any place worth going.', a: 'Beverly Sills' },
  { q: 'Start where you are. Use what you have. Do what you can.', a: 'Arthur Ashe' },
  { q: 'Yoga is the journey of the self, through the self, to the self.', a: 'Bhagavad Gita' },
  { q: 'Change is the end result of all true learning.', a: 'Leo Buscaglia' },
  { q: "Opportunities don't happen. You create them.", a: 'Chris Grosser' },
  { q: "Don't wish it were easier. Wish you were better.", a: 'Jim Rohn' },
  { q: 'The difference between ordinary and extraordinary is that little extra.', a: 'Jimmy Johnson' },
  { q: 'Perseverance is not a long race; it is many short races one after the other.', a: 'Walter Elliot' },
  { q: 'Be stronger than your excuses.', a: 'Unknown' },
  { q: 'First, solve the problem. Then, write the code.', a: 'John Johnson' },
  { q: 'Nature does not hurry, yet everything is accomplished.', a: 'Lao Tzu' },
  { q: 'Wake up with determination. Go to bed with satisfaction.', a: 'Unknown' },
  { q: 'An hour of focused study beats three hours of distracted study.', a: 'Unknown' },
  { q: 'The expert in anything was once a beginner.', a: 'Helen Hayes' },
  { q: 'Motivation gets you going, but discipline keeps you growing.', a: 'John C. Maxwell' }
];
